### ISSUE TITLE
IPFS API is Offline for Firefox, but not Chrome. IPFS desktop daemon and CLI are running fine.

### ISSUE THREAD

**Issue by fellowish** [ipfs-shipyard/ipfs-companion#952] opened 2020-12-27 11:00 UTC
I wanted to get back into using IPFS, and decided to update and install IPFS on Firefox, my main web browser. Unfortunately, no matter what I do (including but not limited to reinstallation of both the desktop daemon and the CLI daemon) it has no effect. Firefox cannot connect to the local gateway for some reason, however Chrome can.

Chrome's localhost is set to the same localhost that the Firefox companion is set to. Moreover, attempting to turn on the localhost capabilities within the settings of IPFS in browser causes an error message to pop up, stating that its API is set to offline automatically as a fallback.

**To Reproduce**:
1. Install desktop daemon
2. Install Firefox companion add-on
3. Note that the companion is not functioning
4. Interestingly, the embedded experimental feature shows IPFS as coming online, and shows peers. Unfortunately, it doesn't seem to have any effect on any pages.

**Expected behavior**:
I wish to have IPFS running on Firefox. It's currently... actually just unusable in its current state. I have installed the latest version of the plugin, have not set firewalls blocking access for Firefox to any ports, have installed the latest version of the desktop daemon, and have not changed any settings for either the IPFS daemon nor the IPFS companion.

**Screenshots**:
![image](https://user-images.githubusercontent.com/28973978/103169347-577de380-4800-11eb-8175-0fbb7c4ae12b.png)
![image](https://user-images.githubusercontent.com/28973978/103169353-62387880-4800-11eb-84fb-cba3209175a5.png)

**Desktop**:
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [Firefox v. 85.0b4; Windows 10 v. 1909]

**Comment by jessicaschilling** [comment] 2020-12-27 14:51
Thank you for the detailed report. Many of the core team are at reduced capacity for the holidays, so it's suggested to open this as a post in the forums at discuss.ipfs.io so your question can be more easily seen by the community as a whole. Thank you!

**Comment by lidel** [comment] 2021-01-02 01:25
This seems to be a duplicate of https://github.com/ipfs-shipyard/ipfs-companion/issues/955 (Firefox 85.0b4) – let's continue there.

@fellowish  a workaround for now is to use Firefox Stable (84)

**Closed by lidel** 2021-01-02 01:25 UTC
Labels: need/triage

**Comment by rafalohaki** [comment] 2023-10-26 10:18
have the same problem
