### ISSUE TITLE
Cannot set v6 address to "IPFS API URL"

### ISSUE THREAD

**Issue by Tacumi** [ipfs-shipyard/ipfs-companion#904] opened 2020-06-28 03:00 UTC
**Describe the bug**
I can't set "http://[::1]:5001" to IPFS API URL.

**To Reproduce**
1. Enter target string to textarea.
2. System said that "Can't construct address: Invalid URL"

**Expected behavior**
Textarea allows IPv6 address.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: latest Brave
 - Version: 1.10.97 Chromium: 83.0.4103.116（Official Build） (64-bit)

**Comment by lidel** [comment] 2020-07-06 19:07
Thank you for reporting this, I confirm this is a bug.

- Error occurs inside of `ipfs-http-client` 
  - This looks like a regression I believe we fixed it once in the past in https://github.com/ipfs-shipyard/ipfs-companion/issues/668
  - Perhaps problem will go away after we switch to the latest version – retry after finishing #811 
    - If someone wants to help, then checking if latest `ipfs-http-client` can talk to `http://[::1]:5001` and commenting here would be useful.

**Comment by lidel** [comment] 2020-10-19 23:42
- ipfs-http-client creates valid ipv6 URLs so I'll removed custom fixups in https://github.com/ipfs-shipyard/ipfs-companion/pull/931
- go-ipfs does not recognize `http://[::1]:5001` as localhost Origin and returns 403 Forbidden error:
  > ![2020-10-19--23-01-50](https://user-images.githubusercontent.com/157609/96521286-341f4100-1271-11eb-999d-015057cc74c7.png) 
  - I fixed that in https://github.com/ipfs/go-ipfs/pull/7731 but we need to wait for new go-ipfs release

**Comment by lidel** [comment] 2020-11-18 20:38
This will ship in v2.16 but will require go-ipfs 0.8+ to be fully fixed.
Closing just for sake of clarity that nothing else is left to do in ipfs-companion.

**Closed by lidel** 2020-11-18 20:38 UTC
Labels: P3, dif/medium, effort/hours, help wanted, kind/bug, need/analysis, status/blocked/upstream-bug
