### ISSUE TITLE
Accessing `window.ipfs` from another extension

### ISSUE THREAD

**Issue by alexander255** [ipfs-shipyard/ipfs-companion#730] opened 2019-07-07 18:08 UTC
I have an extension that needs to periodically update some data file in the background – preferably I'd like to use IPFS and IPFS Companion in the next version for this (falling back to local API or `https://ipfs.io/` if the extension is not installed).
Is this a possible/supported scenario by the *IPFS Companion* extension?
By reading the source code I've found that I can use

```js
let port = browser.runtime.connect("ipfs-firefox-addon@lidel.org", { name: "ipfs-proxy" })
```
to connect to your extension at runtime, but I'm not sure what to do next. Somehow I'd need to `enable` access if I read the source correctly, after this I'd be able to use `cat` to read the file contents in question. Unfortunately I have no idea which exact JSON format I'd have to send to make this happen. Could you give me some tips on this? How stable is the `ipfs-proxy` “Port API”? Can I rely on this working for some time?

Sincerely,
Alexander

**Comment by lidel** [comment] 2019-07-10 13:27
I am afraid it is not possible right now: `ipfs-proxy` is only used by [`window.ipfs`](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/docs/window.ipfs.md) which is experimental (#589) and we don't expose it to other extensions (yet). 

We are tracking ways to provide API for other browser extensions in https://github.com/ipfs-shipyard/ipfs-companion/issues/307. I am closing this issue as a duplicate of https://github.com/ipfs-shipyard/ipfs-companion/issues/307, but would appreciate if you commented there with a description of your use case (what do you use IPFS for, what API commands you extension needs etc)

Thank you!

**Closed by lidel** 2019-07-10 13:27 UTC
