### ISSUE TITLE
Bug: Adding images to ipfs sometimes adds the entire page instead

### ISSUE THREAD

**Issue by swedneck** [ipfs-shipyard/ipfs-companion#579] opened 2018-09-16 21:48 UTC
For example, try right clicking the github logo and adding it to IPFS.

**Comment by lidel** [comment] 2018-09-18 17:07
Thank you for reporting this!
Already tracked in https://github.com/ipfs-shipyard/ipfs-companion/issues/351 (but your title was beater so copied it there :+1: )

**Comment by lidel** [comment] 2018-09-18 17:09
I thought this is duplicate of https://github.com/ipfs-shipyard/ipfs-companion/issues/351 but I think it is separate UX problem.


When image is also a link "Add to IPFS" picks URL of  a link. 
I guess user's expectation is to add image instead, so URL lookup heuristic should be changed.

**Closed** 2018-10-02 00:08 UTC
Labels: UX, bug, good first issue, help wanted, in progress
