### ISSUE TITLE
CIDv1 isn't recognized by window.ipfs.object API

### ISSUE THREAD

**Issue by fiatjaf** [ipfs-shipyard/ipfs-companion#628] opened 2018-11-23 04:58 UTC
I can't give you more information now because my node is crashing and along with it my Companion, but I'll open this issue anyway or I'll forget about it.

**Comment by lidel** [comment] 2018-11-24 14:33
@fiatjaf wow, I really want to know more!
Mind sharing the CID that caused those issues, or steps for how to reproduce?

(even if this is just UX or misconfiguration issue, we should improve behavior/errors/logs)

**Comment by lidel** [comment] 2018-11-24 22:56
@fiatjaf turns out this is actually expected behavior of **ipfs.object.stat** @ [API v0.86.0](https://github.com/ipfs/interface-ipfs-core/blob/v0.86.0/SPEC/OBJECT.md#objectstat).

Some old APIs do not accept CID and only work with raw Multihash and this is one of them:


You need to 

```js
let multihash = new CID('zdj7WWfEyho5nydUR6sZEqAWxEUsL8kCVUrZSAZPPeLcVcSrL').multihash
let stats = await ipfs.object.stat(multihash)
```

**Comment by lidel** [comment] 2018-11-24 23:59
@fiatjaf Thank you for reporting this!

Turns out this is actually expected behavior of **ipfs.object.stat** @ [API v0.86.0](https://github.com/ipfs/interface-ipfs-core/blob/v0.86.0/SPEC/OBJECT.md#objectstat).

Some old APIs do not accept CIDv1 and only work with raw multihash (CIDv0) and this is one of them:
`ipfs.object.stat(multihash, [options, callback])`


If you really need to use this API with CIDv1, import [cids](https://github.com/ipld/js-cid) library and try getting CID's multihash like this:

```js
let multihash = new CID('zdj7WWfEyho5nydUR6sZEqAWxEUsL8kCVUrZSAZPPeLcVcSrL').multihash
let stats = await ipfs.object.stat(multihash)
```

I created a proposal to add support for CIDv1 so the conversion step is not needed: 

- [RFC: OBJECT API should accept CIDv1](https://github.com/ipfs/interface-ipfs-core/issues/397)

As this is an upstream problem not related to ipfs-companion, so I am closing this issue. 
If you want to follow up on this, comment/subscribe to RFC issue linked above.

**Closed by lidel** 2018-11-24 23:59 UTC
Labels: window.ipfs

**Comment by lidel** [comment] 2018-11-25 00:53
@fiatjaf  I feel you should ask this question in a new issue at https://github.com/ipfs/interface-ipfs-core/issues. The last time I looked into this, the DAG API aimed to eventually replace OBJECT API, so feedback on what is missing should be valuable.
