### ISSUE TITLE
Doesn't redirect open tabs with *.localhost urls to public gateway 

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-shipyard/ipfs-companion#894] opened 2020-06-12 22:50 UTC
**Describe the bug**
If there's an open tab, with an URL like `http://cluster.ipfs.io.ipns.localhost/` and refreshed while the local gateway is unavailable (detected by the plugin) there would be just an error page showing "err connection refused".

When URLs like this are open in a new tab, the same thing occurs.

**To Reproduce**
1. Disable local gateway
2. Click on a link like [this](http://cluster.ipfs.io.ipns.localhost)
3. See error "ERR_CONNECTION_REFUSED"

**Expected behavior**
The plugin will recognize the IPNS URL and the status of the local gateway and rewrite the URL to load it from a public gateway instead.

**Screenshots**
![Screenshot_20200613_004939](https://user-images.githubusercontent.com/614929/84552057-cf2a6c00-ad0f-11ea-8f87-fe67ccda648c.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave
 - Version: 1.9.80 Chromium: 81.0.4044.138 (Official Build)

**Comment by lidel** [comment] 2020-06-13 12:40
Thank you for filling this. I believe this is a duplicate of #806, so closing this one.

(if we had IPFS-aware error page, user would be able to recover from this. we should not redirect to public HTTP server, unless user explicitly chose that)

**Closed by lidel** 2020-06-13 12:40 UTC
Labels: status/duplicate
